### ISSUE TITLE
Notify data set changed

### ISSUE THREAD

**Issue by blazsolar** [jakenjarvis/Android-OrmLiteContentProvider#10]
There is an issue when I want to use OrmLiteDefaultContentProvider inside SyncAdapter. OrmLiteDefaultContentProvider calls ContentResolver#notifyDataSetChanged() method, but there is no way to set syncToNetwork parameter to false, so that sync would not happen again.

**Comment by jakenjarvis** [comment]
Hello, @blazsolar
Thank you for your feedback. Hmm, I have not ever used a SyncAdapter.
Is that you wish this?

```
this.getContext().getContentResolver().notifyChange(uri, null, true);
```

My understanding correct?
If my fix this, you happy? but, did not test this code.
https://github.com/jakenjarvis/Android-OrmLiteContentProvider/commit/4a66f15c49d2b9cf9496edc1372af24e81e4aff0

@stephanenicolas
Why was the utterance erased? :)

---

My native language is Japanese. Support of a foreign language is not sufficient.
I'm using a machine translation. Please write in English polite. Ability of my English is not high. XD

**Comment by jakenjarvis** [comment]
Hi, @blazsolar
See https://github.com/jakenjarvis/Android-OrmLiteContentProvider/commit/a96abe1cc82fbdbf4e07d822d1c37292d1f5eca8

**Comment by blazsolar** [comment]
Looks great, thanks.
