### ISSUE TITLE
Database model ID column

### ISSUE THREAD

**Issue by alexis-** [jakenjarvis/Android-OrmLiteContentProvider#16]
Hi,

First of all, great library, thanks for your work.

On topic : Why is it mandatory for the ID column to be @generatedId ?

This gave me trouble and I brought some modifications to the ID-check part in TableInfo.java, as detailed below :

```
// check id
if (columnInfo.getColumnName().equals(BaseColumns._ID) ||
        classfield.getAnnotation(DatabaseField.class).generatedId() ||
        classfield.getAnnotation(DatabaseField.class).id())
  this.idColumnInfo = columnInfo;
```

Can you see this leading to any kind of issue ?

**Comment by jakenjarvis** [comment]
Thank you for reporting. and, sorry reply is now late.
This issue is the same as #11.
If you want to avoid the problem, please try the "1.0.4-SNAPSHOT".
