### ISSUE TITLE
Does Android-OrmLiteContentProvider supports foreign fields?

### ISSUE THREAD

**Issue by suntehnik** [jakenjarvis/Android-OrmLiteContentProvider#18]
I think I should use @ProjectionMap(value= "foreign_field_id")

**Comment by jakenjarvis** [comment]
@suntehnik
I could not understand your intentions. Please explain a little more your ideas.
I'm not good at English. I'm hoping to polite and short sentences English.
When you describe the source code, I'll be easy to understand it. XD
Thanks!
