### ISSUE TITLE
OrmLiteSimpleContentProvider query builder redundancy

### ISSUE THREAD

**Issue by jasco** [jakenjarvis/Android-OrmLiteContentProvider#2]
In OrmLiteSimpleContentProvider.onQuery an ITEM query uses Builder.appendWhere to manually combine the specified item id with the query selection.  However the Builder.query call also combines the selection with any [appendWhere](http://developer.android.com/reference/android/database/sqlite/SQLiteQueryBuilder.html#appendWhere(java.lang.CharSequence\)) clause. This might be a simple redundancy if not for the fact that the manually appended query selection does not take into account selection arguments.

Is there any particular reason the selection is included in the appendWhere?  Maybe there was some legacy issue or something...

**Comment by jakenjarvis** [comment]
Hello, @jasco
Although I am not checking it, probably this is redundant. 

``` java
    if (parameter.getSelection() != null && parameter.getSelection().length() >= 1) {
        where += " AND ( " + parameter.getSelection() + " ) ";
    }
```

I feel like, remained by my mistake is old source code. So there is no legacy issue.(I do not know it at least)
Before the next version, I will fix this.
I would like to thank your bug report. :)

**Comment by jasco** [comment]
Upon closer examination, I see the surrounding functions all use SQLiteDatabase directly which does not concatenate where clauses like the QueryBuilder.  I will submit a pull request.

I think the rest of the functions may need to have the where clauses parameterized, but perhaps that is for separate issue.

**Comment by jakenjarvis** [comment]
I thought your fix is good. Perhaps no problem with it.
Hmm, Seems to be misuse is many sample program. I thought, proper use of appendWhere and appendWhereEscapeString is important.(For the avoidance of SQL Injection)
