### ISSUE TITLE
Module '*-compliler.1.0.4' depends on one or more Android Libraries but is a jar

### ISSUE THREAD

**Issue by hieple7985** [jakenjarvis/Android-OrmLiteContentProvider#22]
Module 'com.tojc.ormlite.android:ormlite-content-provider-compiler:1.0.4' depends on one or more Android Libraries but is a jar
:app:prepareDebugDependencies FAILED

**Comment by Proper-Job** [comment]
Did you add both the library `com.tojc.ormlite.android:ormlite-content-provider-library:1.0.4` and the compiler?

**Comment by hieple7985** [comment]
Yes, I already added "library" and "compiler" then I got it. But If I just added library is everything seems to be OK. Then, some guideline from you can be completed without compiler for generating.

**Comment by Proper-Job** [comment]
I'm sorry, I'm a bit unclear on what you are saying.
You probably need a library for annotation processing if you're using the compiler.

Have you got an annotation processor, such as https://bitbucket.org/hvisser/android-apt installed?

You would need something like the following in your gradle file:

```
// Needed for annotations processing
apply plugin: 'com.neenbedankt.android-apt'
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
    }
}
apt {
    arguments {
        resourcePackageName android.defaultConfig.applicationId
        androidManifestFile variant.outputs[0]?.processResources?.manifestFile
    }
}

dependencies {
    apt 'com.tojc.ormlite.android:ormlite-content-provider-compiler:1.0.4'
    compile 'com.tojc.ormlite.android:ormlite-content-provider-library:1.0.4'
}
```

**Comment by debaj** [comment]
I had the same issue when I had

```
compile "com.tojc.ormlite.android:ormlite-content-provider-library:1.0.4@aar"
compile "com.tojc.ormlite.android:ormlite-content-provider-compiler:1.0.4"
```

in my Gradle script. Replace it with

```
compile "com.tojc.ormlite.android:ormlite-content-provider-library:1.0.4@jar"
compile "com.tojc.ormlite.android:ormlite-content-provider-compiler:1.0.4"
```

and you are all set.

**Comment by hieple7985** [comment]
The project is no longer actively. Just close it.
