### ISSUE TITLE
foreign = true doesn't work

### ISSUE THREAD

**Issue by BigMichi1** [jakenjarvis/Android-OrmLiteContentProvider#4]
i have two tables

``` java
@DatabaseTable(tableName = Contract.Car.TABLENAME)
@DefaultContentUri(authority = Contract.AUTHORITY, path = Contract.Car.CONTENT_URI_PATH)
@DefaultContentMimeTypeVnd(name = Contract.Car.MIMETYPE_NAME, type = Contract.Car.MIMETYPE_TYPE)
public class Car {
    @DatabaseField(columnName = Contract.Car._ID, generatedId = true)
    @DefaultSortOrder
    private int id;
    @DatabaseField(canBeNull = false)
    private String name;
    @DatabaseField(canBeNull = false, foreign = true)
    private Fuel fuel;
}
```

and 

``` java
@DatabaseTable(tableName = Contract.Fuel.TABLENAME)
@DefaultContentUri(authority = Contract.AUTHORITY, path = Contract.Fuel.CONTENT_URI_PATH)
@DefaultContentMimeTypeVnd(name = Contract.Fuel.MIMETYPE_NAME, type = Contract.Fuel.MIMETYPE_TYPE)
public class Fuel {
    @DatabaseField(columnName = Contract.Fuel._ID, generatedId = true)
    @DefaultSortOrder
    private int id;
    @DatabaseField(canBeNull = false, unique = true)
    private String name;
}
```

when i now do:

``` java
getActivity().getContentResolver().query(Contract.Car.CONTENT_URI, null, null, null, null);
```

this query is build, which doesn't respect the foreign field, so that this one fails because the table is created with the field fuel_id instead of fuel 

``` sql
SELECT _id, fuel, name FROM car ORDER BY _id
```

also with foreignAutoRefresh = true it doesn't work

**Comment by jakenjarvis** [comment]
Hello, @BigMichi1

I confirmed it to make a sample program.

This is the Issue of ORMLite and AndroidAPI.
Android-OrmLiteContentProvider is not involved in it.
android.content.ContentResolver#query() does not support 'foreign' probably.

I have confirmed that it works on the following programs.

```
@Override
public void onCreate(SQLiteDatabase database, ConnectionSource connectionSource) {
    try {
        TableUtils.dropTable(connectionSource, Car.class, true);
        TableUtils.dropTable(connectionSource, Fuel.class, true);
        TableUtils.createTableIfNotExists(connectionSource, Car.class);
        TableUtils.createTableIfNotExists(connectionSource, Fuel.class);

        final Dao<Car, Integer> carDao = this.getDao(Car.class);
        final Dao<Fuel, Integer> fuelDao = this.getDao(Fuel.class);

        Fuel fuel = new Fuel("45L");
        fuelDao.create(fuel);

        Car car = new Car("PRIUS", fuel);
        carDao.create(car);

        for (Car targetcar : carDao.queryForAll()) {
            Log.d("", targetcar.getName());
            // need foreignAutoRefresh = true
            Fuel targetfuel = targetcar.getFuel();
            Log.d("", targetfuel.getName());
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
}
```

It must be implemented by this Helper class.
Because there is no way to get the DAO object from Activity, it would have to be devised in the interface of the content provider.

You should contact the community of ORMLite-Android. Probably, you will get the appropriate response.
https://groups.google.com/forum/?hl=ja#!forum/ormlite-android

**Comment by jakenjarvis** [comment]
Please check it.(branch: Issue4_VerificationTest)
https://github.com/jakenjarvis/Android-OrmLiteContentProvider/tree/Issue4_VerificationTest/ormlite-content-provider-compiler-sample

**Comment by jakenjarvis** [comment]
Oops! sorry. I was half asleep.
If you are using OrmLiteSimpleContentProvider, You might be solved by overriding the OrmLiteSimpleContentProvider#onQuery().

OrmLiteSimpleContentProvider is a simple implementation for performing standard processing. If you ask the complexity further, you select the options below:
- You to override the OrmLiteSimpleContentProvider.
- You to create a ContentProvider class that inherits OrmLiteDefaultContentProvider.

**Comment by jakenjarvis** [comment]
I was worried about, I tried to implement. It has not been enough testing, but will work with this.
https://github.com/jakenjarvis/Android-OrmLiteContentProvider/blob/Issue4_VerificationTest/ormlite-content-provider-compiler-sample/src/com/tojc/ormlite/android/ormlitecontentprovider/compiler/sample/provider/MyProvider.java#L65

Issue of you will be solved in this. ;D
