### ISSUE TITLE
Can't get this working with Android Studio

### ISSUE THREAD

**Issue by alistairrutherford** [jakenjarvis/Android-OrmLiteContentProvider#5]
No matter what I try I cannot seem to get rid of the error

Gradle: : duplicate files during packaging of APK 

I have tried excluding the orm-lite classes from the components i.e.

compile 'com.j256.ormlite:ormlite-android:4.47'

compile 'com.j256.ormlite:ormlite-core:4.47'

compile group: 'com.tojc.ormlite.android', name: 'ormlite-content-provider-library', version: '1.0.3'  exclude group: 'com.j256.ormlite'

compile group: 'com.tojc.ormlite.android', name: 'ormlite-content-provider-compiler', version: '1.0.3' exclude group: 'com.j256.ormlite'

But to no avail. If you create a dummy application using android studio and add these dependancies you will be able to recreate the error.

**Comment by jakenjarvis** [comment]
I have not ever used a AndroidStudio still. Near future, I would try it.

**Comment by alistairrutherford** [comment]
I figured it out. Not sure if my comment got posted it not. The android
manifest XML file in the component is clashing with the one in the client
project. The apklib setting in your sample project handles this but there
does not appear to be an equivilant in gradle. Oh well.

Best Regards
Alistair

**Comment by jakenjarvis** [comment]
Since I have generated a ormlite-content-provider-library-1.0.3.jar in Maven, you will be able to use it.
http://repo1.maven.org/maven2/com/tojc/ormlite/android/ormlite-content-provider-library/1.0.3/
That you use this or is difficult in the AndroidStudio?

My native language is Japanese. Support of a foreign language is not sufficient.
I'm using a machine translation. Please write in English polite. Ability of my English is not high. XD

**Comment by alistairrutherford** [comment]
It is working now. I used provided jar and link to it locally using:

 compile files('lib/ormlite-content-provider-library-1.0.3.jar')

Thanks.

**Comment by jakenjarvis** [comment]
Oh, it was good! I thank you for your report you. :)

**Comment by jakenjarvis** [comment]
Hi @alistairrutherford 
I checked it by AndroidStudio. Your problem will be solved by the following description. ;)

```
dependencies {
    compile 'com.tojc.ormlite.android:ormlite-content-provider-library:1.0.3@jar'
}
```
