### ISSUE TITLE
Can't build on windows.

### ISSUE THREAD

**Issue by alistairrutherford** [jakenjarvis/Android-OrmLiteContentProvider#6]
If you download the source to a Windows machine it will not build. The checkstyle component is flagging up an error: "File does not end with a newline" on all the files in the ormlite-content-provider-library project. The solution is to switch off the "NewlineAtEndOfFile" check in the style_checks.xlm file.Not sure what you can do about this but I thought I'd point it out.

**Comment by alistairrutherford** [comment]
Okay, I have figured it out. The clash is between the AndroidManifest,xml file in my own project and the the one in  "ormlite-content-provider-library". In Maven I  assume the apklib type setting is somehow handling this but I have no idea how you define this in Gradle so that it excluded the library project AndroidManifest,xml file.

**Comment by jakenjarvis** [comment]
I have not yet created, the configuration file of Gradle. In order for you to use OrmLiteContentProvider in AndroidStudio, you will have to make it.
And, You should probably use the jar.

For ApkLib, please refer to here.
http://code.google.com/p/maven-android-plugin/wiki/ApkLib

**Comment by alistairrutherford** [comment]
Apologies my comment above was for issue #5.
