### ISSUE TITLE
AndroidStudio and Gradle Support

### ISSUE THREAD

**Issue by jakenjarvis** [jakenjarvis/Android-OrmLiteContentProvider#7]
AndroidStudio and Gradle Support.
#5 #6

**Comment by gbero** [comment]
Hi, did you already published the aar to maven central ?

**Comment by jakenjarvis** [comment]
Wow, and this has been in that the logs are terrible. X(

Hi, @gbero
I'm sorry. The next release is delayed. I have been little busy.
If you use the instead JAR of AAR, please try the following procedure.

```
dependencies {
    compile 'com.tojc.ormlite.android:ormlite-content-provider-library:1.0.3@jar'
}
```

**Comment by gbero** [comment]
Thanks for your answer. Is it possible to use also the 'compiler' with the JAR only ?

**Comment by jakenjarvis** [comment]
@gbero Yes, you can. ormlite-content-provider-compiler is not an Android project. :)
