### ISSUE TITLE
Using OrmLiteContentProvider with library that uses OrmLite

### ISSUE THREAD

**Issue by dant3** [jakenjarvis/Android-OrmLiteContentProvider#8]
Hi. I have a library that uses ormlite to implement entities and business logic on working with them, and now I want to display content of it's database on Android.
I can't influence the library source code much, and this library used as well by other platforms: swing desktop app and spring servlet. The library is somewhat configurable - I can inject custom interface implementations for storage for example - it isn't tied to database. Also I can tune database connection. That I can't tune is entities with their tables and fields configuration, which is a part of library.

Any ideas/hints on how can I use ormlite-content-provider in such sutiation to achieve access to database from views?
Any chances to generate Contracts automatically?

**Comment by jakenjarvis** [comment]
Hi, @dant3
First, I may not have understood your intentions. In the same way, To convey the intent to you from me is difficult.
My native language is Japanese. Support of a foreign language is not sufficient. I'm using a machine translation.(Accuracy is very low... Often, it will be a strange translation results)

> Any ideas/hints on how can I use ormlite-content-provider in such sutiation to achieve access to database from views?

I feel like you are asking me how to use the Content Provider. Unfortunately, I will not be able to explain it.
This is not a library needed to use the ORMLite.(In other words, this is not the only way) This library helps you to create a Content Provider using ORMLite.
I have a common part that everyone must implement. This library is a thin wrapper with the habit of Android-specific.

Probably, how to use standard Content Provider in Android, you would need to understand.
See, Android Developers : Content Provider
http://developer.android.com/guide/topics/providers/content-providers.html

If you implement the function using the Content Provider, this library will help you. :D
